version: '3.8'

services:

  gdata.messages.svc:
    container_name: gdata-message-broker-svc
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672
    volumes:
      - .data:/var/bitnami
    environment:
      - "RABBITMQ_USERNAME=user"
      - "RABBITMQ_PASSWORD=Pa55W0rld"
    restart: on-failure
    networks:
      - infrastructure

  gdata.pipeline.svc:
    container_name: gdata-pipeline-svc
    restart: on-failure:2
    cap_drop:
      - ALL
    cap_add:
      - CAP_NET_BIND_SERVICE
    environment:
      - APP_ENVIRONMENT=Development
    networks:
      - infrastructure

networks:
  infrastructure:
    name: gdp-infrastructure
